// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPZmvW9K9EgBRwBTebQx9OM5X4u3b2Nf0',
    appId: '1:1069283303095:web:147852d98c2bd3cefab732',
    messagingSenderId: '1069283303095',
    projectId: 'dojo-manager-2bf1a',
    authDomain: 'dojo-manager-2bf1a.firebaseapp.com',
    storageBucket: 'dojo-manager-2bf1a.firebasestorage.app',
    measurementId: 'G-1XJPB2SHJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvuf13PvYzeL47znMxS_7J82UcxhztNa4',
    appId: '1:1069283303095:android:66327a69b11a59affab732',
    messagingSenderId: '1069283303095',
    projectId: 'dojo-manager-2bf1a',
    storageBucket: 'dojo-manager-2bf1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWTWEFxr6wba4So2V5JD34nE0IBOMb0oU',
    appId: '1:1069283303095:ios:f9b80ee6b473d2aafab732',
    messagingSenderId: '1069283303095',
    projectId: 'dojo-manager-2bf1a',
    storageBucket: 'dojo-manager-2bf1a.firebasestorage.app',
    iosBundleId: 'com.example.dojoManager',
  );
}
